apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
spec: # doit estre pareil que le pv
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
